version: '3.8'
services:
  helpdesk:
    image: 'mysql:latest'
    container_name: 'helpdesk'
    environment:
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: root
    ports:
      - 3306:3306
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"  # Map container's port 80 to host's port 1080
      - "1025:1025"  # Map container's port 25 to host's port 1025
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
